version: 2

jobs:
  Apollo Server:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?
      - run:
          name: Starting server
          command: npm run start:ci
          background: true
      - run: sleep 5
      - run: npx apollo service:check
      - run: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npx apollo service:push
          fi

  CoPilot:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - deploy:
          command: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle2/scripts/upload)

  Heroku Deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: |
          if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master
          fi

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Server
      - CoPilot:
          requires:
            - Apollo Server
      - Heroku Deploy:
          requires:
            - CoPilot
